# General MIDI Level 1 PERCUSSION KEY MAP
# REF: https://www.midi.org/specifications-old/item/gm-level-1-sound-set
GM1_FULL_MAP = {
    "Acoustic_Bass_Drum": [35],
    "Bass_Drum_1": [36],
    "Side_Stick": [37],
    "Acoustic_Snare": [38],
    "Hand_Clap": [39],
    "Electric_Snare": [40],
    "Low_Floor_Tom": [41],
    "Closed_Hi_Hat": [42],
    "High_Floor_Tom": [43],
    "Pedal_Hi-Hat": [44],
    "Low_Tom": [45],
    "Open_Hi-Hat": [46],
    "Low-Mid_Tom": [47],
    "Hi-Mid_Tom": [48],
    "Crash_Cymbal_1": [49],
    "High_Tom": [50],
    "Ride_Cymbal_1": [51],
    "Chinese_Cymbal": [52],
    "Ride_Bell": [53],
    "Tambourine": [54],
    "Splash_Cymbal": [55],
    "Cowbell": [56],
    "Crash_Cymbal_2": [57],
    "Vibraslap": [58],
    "Ride_Cymbal_2": [59],
    "Hi_Bongo": [60],
    "Low_Bongo": [61],
    "Mute_Hi_Conga": [62],
    "Open_Hi_Conga": [63],
    "Low_Conga": [64],
    "High_Timbale": [65],
    "Low_Timbale": [66],
    "High_Agogo": [67],
    "Low_Agogo": [68],
    "Cabasa": [69],
    "Maracas": [70],
    "Short_Whistle": [71],
    "Long_Whistle": [72],
    "Short_Guiro": [73],
    "Long_Guiro": [74],
    "Claves": [75],
    "Hi_Wood_Block": [76],
    "Low_Wood_Block": [77],
    "Mute_Cuica": [78],
    "Open_Cuica": [79],
    "Mute_Triangle": [80],
    "Open_Triangle": [81]
}

# MAGENTA MAPPING
ROLAND_REDUCED_MAPPING = {
    "KICK": [36],
    "SNARE": [38, 37, 40],
    "HH_CLOSED": [42, 22, 44],
    "HH_OPEN": [46, 26],
    "TOM_3_LO": [43, 58],
    "TOM_2_MID": [47, 45],
    "TOM_1_HI": [50, 48],
    "CRASH": [49, 52, 55, 57],
    "RIDE":  [51, 53, 59]
}

# https://bernhard.hensler.net/roland-td-11-setup-midi-mapping/
# REF: https://rolandus.zendesk.com/hc/en-us/articles/360005173411-TD-17-Default-Factory-MIDI-Note-Map
ROLAND_TD_17_Full_map = {
    "KICK": [36],
    "SNARE_HEAD": [38],
    "SNARE_RIM": [40],
    "SNARE_X_Stick": [37],
    "TOM_1": [48],
    "TOM_1_RIM": [50],
    "TOM_2": [45],
    "TOM_2_RIM": [47],
    "TOM_3_HEAD": [43],
    "TOM_3_RIM": [58],
    "HH_OPEN_BOW": [46],
    "HH_OPEN_EDGE": [26],
    "HH_CLOSED_BOW": [42],
    "HH_CLOSED_EDGE": [22],
    "HH_PEDAL": [44],
    "CRASH_1_BOW": [49],
    "CRASH_1_EDGE": [55],
    "CRASH_2_BOW": [57],
    "CRASH_2_EDGE": [52],
    "RIDE_BOW": [51],
    "RIDE_EDGE": [59],
    "RIDE_BELL": [53]
}
