experiment: 'InfillingClosedHH_Symbolic'
batch_size: 64
d_model: 16
dim_feedforward: 512
dropout: 0.28
optimizer_algorithm: 'sgd'
learning_rate: 0.05
n_heads: 8
num_encoder_decoder_layers: 6
epochs: 500
encoder_only: 1
hit_loss_penalty: 0.23
load_model: Null