experiment: 'InfillingClosedHH_Symbolic'
batch_size: 64
d_model: 256
dim_feedforward: 128
dropout: 0.17
optimizer_algorithm: 'sgd'
learning_rate: 0.067
n_heads: 8
num_encoder_decoder_layers: 8
epochs: 500
encoder_only: 1
hit_loss_penalty: 0.40
load_model: Null