encoder_only: 1
optimizer_algorithm: 'sgd'
d_model: 64
n_heads: 16
dropout: 0.2
num_encoder_decoder_layers: 7
hit_loss_penalty: 1
batch_size: 16
dim_feedforward: 256
learning_rate: 0.05
epochs: 100
load_model: Null