method: random
metric:
  goal: minimize
  name: loss
parameters:
  batch_size:
    values: [16, 32, 64, 128, 256, 512]
  d_model:
    values: [16, 32, 64, 128, 256, 512]
  dim_feedforward:
    values: [16, 32, 64, 128, 256, 512]
  dropout:
    distribution: 'uniform'
    min: 0.1
    max: 0.3
  optimizer_algorithm:
    value: 'sgd'
  learning_rate:
    distribution: 'uniform'
    min: 0
    max: 0.1
  n_heads:
    values: [ 1, 2, 4, 8, 16]
  num_encoder_decoder_layers:
    distribution: 'int_uniform'
    min: 6
    max: 12
  epochs:
    value: 100
  encoder_only:
    value: 1
  experiment:
    value: 'InfillingClosedHH'
  hit_loss_penalty:
    distribution: 'uniform'
    min: 0
    max: 1
program: train.py
project: 'InfillingClosedHH'
description: ''