experiment: 'InfillingClosedHH'
batch_size: 16
d_model: 32
dim_feedforward: 512
dropout: 0.24
optimizer_algorithm: 'sgd'
learning_rate: 0.07
n_heads: 16
num_encoder_decoder_layers: 6
epochs: 400
encoder_only: 1
hit_loss_penalty: 0.38
load_model: Null
# params from zesty-sweep-13